name: Healthcare Automation

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven Packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Install Dependencies
        run: mvn clean install -DskipTests

      - name: Run Cucumber Tests
        run: mvn test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-report
          path: target/